### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [JakeTrans/CSVEditor#15]
Dear @JakeTrans,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by JakeTrans** [comment]
Hi,

generated a release containing the latest code

**Comment by sergeevabc** [comment]
Source: [semicolon-comma.txt](https://github.com/JakeTrans/CSVEditor/files/6259062/semicolon-comma.txt)

![](https://i3.imageban.ru/out/2021/04/05/93a85fda53323b062c963c4a04f9f2fc.png)

**Comment by JakeTrans** [comment]
Thanks, Looking a the file the issue lies with the with there being one header vs two columns of data (currently spilts by comma, rather than semi-colon)

I'll look into this when I get a moment, Thanks

**Comment by JakeTrans** [comment]
New release done, this works with the above file

**Comment by sergeevabc** [comment]
[meals.txt](https://github.com/JakeTrans/CSVEditor/files/6259709/meals.txt)

The same error.

**Comment by JakeTrans** [comment]
simlilar issue, due to having multiple extra headings.

**Comment by JakeTrans** [comment]
Release made for this fix

**Comment by sergeevabc** [comment]
Opens fine via [this][1], [this][2], [this][3], [this][4], and [this][5], not to mention a variety of local CSV viewers/editors. In a word, too buggy to proceed.

[1]: https://www.editcsvonline.com/
[2]: https://lemonunit.github.io/csv-editor-online/
[3]: https://www.becsv.com/csv-viewer.php
[4]: https://limonte.github.io/csv-viewer-online/
[5]: https://codebeautify.org/csv-viewer
